export const TypeColor = {
  'All types': [null, 'bg-gray-3', 'text-white'],
  Water: ['bg-Water-1', 'bg-Water-2', 'text-black'],
  Dragon: ['bg-Dragon-1', 'bg-Dragon-2', 'text-white'],
  Electric: ['bg-Electric-1', 'bg-Electric-2', 'text-black'],
  Fairy: ['bg-Fairy-1', 'bg-Fairy-2', 'text-black'],
  Ghost: ['bg-Ghost-1', 'bg-Ghost-2', 'text-white'],
  Fire: ['bg-Fire-1', 'bg-Fire-2', 'text-black'],
  Ice: ['bg-Ice-1', 'bg-Ice-2', 'text-black'],
  Grass: ['bg-Grass-1', 'bg-Grass-2', 'text-black'],
  Bug: ['bg-Bug-1', 'bg-Bug-2', 'text-black'],
  Fighting: ['bg-Fighting-1', 'bg-Fighting-2', 'text-white'],
  Normal: ['bg-Normal-1', 'bg-Normal-2', 'text-black'],
  Dark: ['bg-Dark-1', 'bg-Dark-2', 'text-white'],
  Steel: ['bg-Steel-1', 'bg-Steel-2', 'text-black'],
  Rock: ['bg-Rock-1', 'bg-Rock-2', 'text-black'],
  Psychic: ['bg-Psychic-1', 'bg-Psychic-2', 'text-black'],
  Ground: ['bg-Ground-1', 'bg-Ground-2', 'text-black'],
  Poison: ['bg-Poison-1', 'bg-Poison-2', 'text-white'],
  Flying: ['bg-Flying-1', 'bg-Flying-2', 'text-black'],
};